"""
Pydantic Schemas for User Rules API

Request/Response models for the /rules endpoints.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class UserRuleStatusEnum(str, Enum):
    """Rule status for API"""
    draft = "draft"
    active = "active"
    deprecated = "deprecated"
    archived = "archived"


# ============================================
# VERSION SCHEMAS
# ============================================

class RuleVersionResponse(BaseModel):
    """Rule version in API responses"""
    id: str
    version_number: int
    version_name: Optional[str] = None
    rule_schema: Dict[str, Any]
    status: str
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================
# RULE TEMPLATE SCHEMAS
# ============================================

class RuleTemplateBase(BaseModel):
    """Base fields for rule templates"""
    rule_name: str = Field(..., min_length=1, max_length=255)
    slug: str = Field(..., min_length=1, max_length=255)
    jurisdiction: str = Field(..., min_length=1, max_length=100)
    trigger_type: str = Field(..., min_length=1, max_length=50)
    description: Optional[str] = None
    tags: Optional[List[str]] = None
    is_public: bool = False


class CreateRuleRequest(RuleTemplateBase):
    """Request body for creating a new rule"""
    rule_schema: Dict[str, Any] = Field(..., description="Full rule schema with deadlines")


class UpdateRuleRequest(BaseModel):
    """Request body for updating a rule"""
    rule_name: Optional[str] = Field(None, max_length=255)
    description: Optional[str] = None
    tags: Optional[List[str]] = None
    is_public: Optional[bool] = None
    rule_schema: Optional[Dict[str, Any]] = None


class RuleTemplateResponse(BaseModel):
    """Rule template in API responses"""
    id: str
    rule_name: str
    slug: str
    jurisdiction: str
    trigger_type: str
    status: UserRuleStatusEnum
    version_count: int
    usage_count: int
    is_public: bool
    is_official: bool
    created_at: datetime
    description: Optional[str] = None
    tags: Optional[List[str]] = None
    version: Optional[RuleVersionResponse] = None

    class Config:
        from_attributes = True


class RuleTemplateListResponse(BaseModel):
    """Response for listing rules"""
    success: bool = True
    data: List[RuleTemplateResponse]
    message: Optional[str] = None


class RuleTemplateDetailResponse(BaseModel):
    """Response for single rule detail"""
    success: bool = True
    data: RuleTemplateResponse
    message: Optional[str] = None


# ============================================
# RULE EXECUTION SCHEMAS
# ============================================

class ExecuteRuleRequest(BaseModel):
    """Request body for executing a rule"""
    rule_template_id: str
    case_id: str
    trigger_data: Dict[str, Any] = Field(..., description="Trigger values, e.g. {'trial_date': '2026-06-01'}")
    dry_run: bool = Field(False, description="If true, preview deadlines without creating")


class GeneratedDeadline(BaseModel):
    """A deadline generated by rule execution"""
    id: str
    title: str
    deadline_date: Optional[str] = None
    priority: str
    rule_citation: Optional[str] = None


class ExecuteRuleResponse(BaseModel):
    """Response from rule execution"""
    deadlines_created: int
    execution_time_ms: int
    rule_name: str
    rule_version: int
    errors: List[str] = []
    deadlines: List[GeneratedDeadline] = []


class ExecuteRuleFullResponse(BaseModel):
    """Full wrapped response for rule execution"""
    success: bool = True
    data: ExecuteRuleResponse
    message: Optional[str] = None


class RuleExecutionRecord(BaseModel):
    """Execution history record"""
    id: str
    rule_template_id: Optional[str] = None
    case_id: Optional[str] = None
    trigger_data: Dict[str, Any]
    deadlines_created: int
    execution_time_ms: Optional[int] = None
    status: str
    error_message: Optional[str] = None
    executed_at: datetime
    deadline_ids: Optional[List[str]] = None

    class Config:
        from_attributes = True


class ExecutionHistoryResponse(BaseModel):
    """Response for execution history"""
    success: bool = True
    data: List[RuleExecutionRecord]
    message: Optional[str] = None


# ============================================
# MARKETPLACE SCHEMAS
# ============================================

class MarketplaceRuleResponse(BaseModel):
    """Rule in marketplace view"""
    id: str
    rule_name: str
    slug: str
    jurisdiction: str
    trigger_type: str
    description: Optional[str] = None
    tags: Optional[List[str]] = None
    usage_count: int
    is_official: bool
    author_name: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


class MarketplaceListResponse(BaseModel):
    """Response for marketplace listing"""
    success: bool = True
    data: List[MarketplaceRuleResponse]
    message: Optional[str] = None


# ============================================
# GENERIC RESPONSES
# ============================================

class SuccessResponse(BaseModel):
    """Generic success response"""
    success: bool = True
    message: Optional[str] = None


class ErrorResponse(BaseModel):
    """Error response"""
    success: bool = False
    message: str
    detail: Optional[str] = None
